### ISSUE TITLE
bug: copied <math> into <graphs> do not work with the anchor attribute

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#2203] opened 2023-06-09 15:04 UTC
If a `<math>` is copied into a graph using the copy macro or the copySource attribute, and an anchor attribute is added, Doenet ignores the anchor. 
A math has to be defined within the graph for the anchor to work

**Comment by dqnykamp** [comment] 2023-06-23 01:08
I cannot reproduce this error.

This DoenetML
```
<math name="m1">x</math>
<graph>
  <math copySource="m1" anchor="(1,2)" />
  $m1{anchor="(3,4)"}
  <copy source="m1" anchor="(5,6)" />
</graph>
```
results with the anchor working correctly:
![image](https://github.com/Doenet/DoenetTools/assets/1037056/77e74e39-4906-4931-aa42-385d52156dca)

I'm closing this issue.  Please reopen if I missed something.

**Closed by dqnykamp** 2023-06-23 01:08 UTC
