### ISSUE TITLE
<figure> and <caption> formatting not consistent with displayMode default

### ISSUE THREAD

**Issue by virginiaMae** [Doenet/DoenetTools#1790] opened 2022-11-03 15:21 UTC
The default displayMode for an image within a figure is centered, but the default displayMode for a \<caption> is still to the left, which leads to an awkward appearance of a trailing caption not attached to the image.

**Comment by keaganeng** [comment] 2022-11-08 23:20
@virginiaMae Can you please provide a screenshot or some sample code?

**Comment by virginiaMae** [comment] 2022-11-11 15:46
Sure! here is a link to the sample 
[https://www.doenet.org/course?tool=editor&doenetId=_sY9H04D5XsWf5Y7n7xj59&pageId=_HuZJfzIqHs9FSqgwTBum7](url)
I changed you to an owner in the course so hopefully you can view this without any problems. Let me know if I need to make a public link instead

**Comment by dqnykamp** [comment] 2022-11-25 15:07
@virginiaMae, can you make a public link or copy some DoenetML here if this isn't correct?  But, I assume the issue is illustrated by this DoenetML, where the image is centered and the caption is to the left.
```
<figure>
   <image source="https://www.doenet.org/media/Doenet_Logo_Frontpage.png"
     description="Doenet Logo" />
   <caption>The Doenet logo</caption>
</figure>
```
![image](https://user-images.githubusercontent.com/1037056/204012061-6637e707-a357-40a5-b39f-f5dbef8cfff8.png)

**Comment by dqnykamp** [comment] 2022-11-25 15:29
First, I see another problem, the fact that **Figure 1:** is on a separate line; it should be all on one line.  An easy fix for this is to change the caption rendererType from `containerBlock` to `containerInline`, which puts the caption inside a `<span>` rather than a `<div>`.

A caption, though, could have block children, such as paragraphs.  So, it's a bit inconsistent to render it with `containerInline`, but it's better than having the extra line break.

**Comment by dqnykamp** [comment] 2022-11-25 15:44
I'm guessing that the ideal behavior is what Latex does.  If a caption is a single line, it is centered.  As soon as a caption spills over to multiple lines, then it is rendered left justified.

I'm not sure if that behavior is possible in html.  I noticed that [PreTeXt renders one line captions left justified](https://pretextbook.org/examples/sample-article/html/section-5.html) like we do.

Assuming we can't figure out how to get Latex's behavior, we could add a flag to `<caption>` , such as a `center` flag.  I don't like that, as that's adding styling information to DoenetML, and DoenetML should be semantic.  The `<caption>` tag is sufficient in giving the semantic for the relationship between the caption content and the figure.

**Comment by dqnykamp** [comment] 2022-11-25 16:26
> First, I see another problem, the fact that **Figure 1:** is on a separate line; it should be all on one line. An easy fix for this is to change the caption rendererType from `containerBlock` to `containerInline`, which puts the caption inside a `<span>` rather than a `<div>`.

I think a better solution is to create a separate caption renderer and have that renderer be responsible for the **Figure 1:** part.  (This will require some reworking inside the Caption component itself.)  Then, the caption can be a block component, as it should be, and the caption renderer could count lines and change its justification depending on the number of lines.

**Comment by dqnykamp** [comment] 2022-11-28 18:23
The `<figure>` component would still control the numbering and whether or not the figure name is in the caption.  But, then the `<caption>` would read that information off its parent `<figure>`.  I don't think the figure renderer would do anything with it though; it would just be the job of the caption renderer.

No, I haven't started implementing anything.  I've just been mulling over ideas of how it might work.  Is this something you'd like me to help with?  I recognize that you aren't yet familiar with core, so you wouldn't know how to make the `<caption>` component grab information from its `<figure>` parent.

**Comment by keaganeng** [comment] 2022-11-29 11:18
> The `<figure>` component would still control the numbering and whether or not the figure name is in the caption. But, then the `<caption>` would read that information off its parent `<figure>`. I don't think the figure renderer would do anything with it though; it would just be the job of the caption renderer.
> 
So, to make sure I'm understanding correctly: the `<figure/>` and the `<caption/>` would both have a displayMode state variable, but `<figure/>` would not? And the default displayMode of both `<figure/>` and the `<caption/>` would be `flex`?
> No, I haven't started implementing anything. I've just been mulling over ideas of how it might work. Is this something you'd like me to help with? I recognize that you aren't yet familiar with core, so you wouldn't know how to make the `<caption>` component grab information from its `<figure>` parent.
>
I'm happy to try to help you with this, but I'm about to take a few weeks off from Doenet for finals and wrapping up my time in Ireland. If this is a more urgent fix, it may be best to start working on it without me. I would also need someone to explain how core works.

**Closed** 2023-01-18 17:55 UTC
